spring:
  application:
    name: tqk-eureka-consumer
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
server:
  port: 9992
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/

